---
name: Gradle


jobs:
  build:
    uses: jburel/.github/workflow-templates/gradle_build.yml@57b69706dbe1f2a6620da8470c5f809231ccb8ec
  publish:
    uses: jburel/.github/workflow-templates/gradle_publish.yml@57b69706dbe1f2a6620da8470c5f809231ccb8ec
