---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    uses: jburel/action-workflows/.github/workflows/gradle_build.yml@40d235da5eb375c828c540c0ad7694a7db1e1e39
  publish_snapshot:
    needs: build
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@40d235da5eb375c828c540c0ad7694a7db1e1e39
    with:
      ARTIFACTORY_URL: "snapshots"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@40d235da5eb375c828c540c0ad7694a7db1e1e39
    with:
      ARTIFACTORY_URL: "staging"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
