---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    uses: jburel/dotgithub/.github/workflows/gradle_build.yml@eb6c97e62ae8d739897ed53bda13f65007a86c6d
  publish:
    uses: jburel/dotgithub/.github/workflows/gradle_publish.yml@eb6c97e62ae8d739897ed53bda13f65007a86c6d
    with:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
