---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    uses: jburel/action-workflows/.github/workflows/gradle_build.yml@a144e3d8152780c36175b39639c1dbd10b3fba0f
  publish_snapshot:
    needs: build
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@a144e3d8152780c36175b39639c1dbd10b3fba0f
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
