---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    uses: jburel/action-workflows/.github/workflows/gradle_build.yml@b294a0d2fe78d0b25662365bec3d6392f3bf4963
  publish_snapshot:
    needs: build
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@b294a0d2fe78d0b25662365bec3d6392f3bf4963
    with:
      ARTIFACTORY_URL: "snapshots"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@b294a0d2fe78d0b25662365bec3d6392f3bf4963
    with:
      ARTIFACTORY_URL: "staging"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
