---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    uses: jburel/action-workflows/.github/workflows/gradle_build.yml@a9f897eb884598993807a7c57e63e1e292da66a8
  publish_snapshot:
    needs: build
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@a9f897eb884598993807a7c57e63e1e292da66a8
    with:
      ARTIFACTORY_URL: "snapshots"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    uses: jburel/action-workflows/.github/workflows/gradle_publish.yml@a9f897eb884598993807a7c57e63e1e292da66a8
    with:
      ARTIFACTORY_URL: "staging"
    secrets:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
