---
name: Gradle


jobs:
  build:
    uses: jburel/dotgithub/workflows/gradle_build.yml@fbf3035ec6e506144ed0929e721c60200993db56
  publish:
    uses: jburel/dotgithub/workflows/gradle_publish.yml@fbf3035ec6e506144ed0929e721c60200993db56
